spring.application.name=PCRemota

# Servidor
server.port=8443
server.address=0.0.0.0

# Base de datos H2 en archivo
spring.datasource.url=jdbc:h2:file:./data/pcremota;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false

# Peticiones HTTP max (para acciones largas como ping)
server.servlet.async.timeout=10000
